[package]
name = "chess"
version = "0.1.0"
authors = ["Xydez <thexydez@gmail.com>"]
edition = "2018"

[features]
default = []
use_ai = []

[dependencies]
gl = "0.14.0"
glfw = "0.41.0"
nalgebra = "0.25.4"
image = "0.23.14"
lazy_static = "1.4.0"
rodio = "0.13.1"
